/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xcv58' at '10/15/15 9:47 AM' with Gradle 2.7
 *
 * @author xcv58, @date 10/15/15 9:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
